project 'Kmong.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Kmong' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Kmong
  
  pod 'SwiftyStarRatingView', '~> 1.0'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'JSQMessagesViewController'
  
  target 'KmongTests' do
    inherit! :search_paths
    pod 'Firebase'
    # Pods for testing
  end

  target 'KmongUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
